# Setup
title:        OpenMTP | Documentations
tagline:      OpenMTP | Android File Transfer for macOS
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Ganesh Rathinavel
  url:        https://ganeshrvel.github.io/openmtp/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
